name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: download .
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: check format
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check

      - name: check linting
        if: matrix.os == 'ubuntu-latest'
        run: deno lint

      - name: run normal tests in parallel
        run: deno task test

      - name: run download tests sequentially
        run: deno task test:download

      - name: pretend to publish package
        run: deno publish --dry-run
